version: '3.10'

services:
  redis:
    image: redis
    restart: always 
  
  
  db:
    restart: always
    image:
      postgres:alpine3.17
    container_name: 
      db_wellp
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=new_db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=matvey

  
  wellpaper-proj:
    restart: always
    build: 
      context: ./wallpaper-proj

    ports:
      - "8000:8000"

    command: ["python3.10", "./myproj/manage.py", "runserver", "0.0.0.0:8000"]
